//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5485.
// 
#pragma warning disable 1591

namespace ValidatePostalCodeWebServiceClient.CountryServiceWebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CountryServiceSoapBinding", Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class CountryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validatePostalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CountryService() {
            this.Url = global::ValidatePostalCodeWebServiceClient.Properties.Settings.Default.ValidatePostalCodeWebServiceClient_CountryServiceWebReference_CountryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validatePostalCompletedEventHandler validatePostalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fedex.com/ws/cnty/v4/validatePostal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ValidatePostalReply", Namespace="http://fedex.com/ws/cnty/v4")]
        public ValidatePostalReply validatePostal([System.Xml.Serialization.XmlElementAttribute(Namespace="http://fedex.com/ws/cnty/v4")] ValidatePostalRequest ValidatePostalRequest) {
            object[] results = this.Invoke("validatePostal", new object[] {
                        ValidatePostalRequest});
            return ((ValidatePostalReply)(results[0]));
        }
        
        /// <remarks/>
        public void validatePostalAsync(ValidatePostalRequest ValidatePostalRequest) {
            this.validatePostalAsync(ValidatePostalRequest, null);
        }
        
        /// <remarks/>
        public void validatePostalAsync(ValidatePostalRequest ValidatePostalRequest, object userState) {
            if ((this.validatePostalOperationCompleted == null)) {
                this.validatePostalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidatePostalOperationCompleted);
            }
            this.InvokeAsync("validatePostal", new object[] {
                        ValidatePostalRequest}, this.validatePostalOperationCompleted, userState);
        }
        
        private void OnvalidatePostalOperationCompleted(object arg) {
            if ((this.validatePostalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validatePostalCompleted(this, new validatePostalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class ValidatePostalRequest {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private System.DateTime shipDateTimeField;
        
        private bool shipDateTimeFieldSpecified;
        
        private Address addressField;
        
        private string routingCodeField;
        
        private bool checkForMismatchField;
        
        private bool checkForMismatchFieldSpecified;
        
        private CarrierCodeType carrierCodeField;
        
        private bool carrierCodeFieldSpecified;
        
        /// <remarks/>
        public WebAuthenticationDetail WebAuthenticationDetail {
            get {
                return this.webAuthenticationDetailField;
            }
            set {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        public ClientDetail ClientDetail {
            get {
                return this.clientDetailField;
            }
            set {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShipDateTime {
            get {
                return this.shipDateTimeField;
            }
            set {
                this.shipDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipDateTimeSpecified {
            get {
                return this.shipDateTimeFieldSpecified;
            }
            set {
                this.shipDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string RoutingCode {
            get {
                return this.routingCodeField;
            }
            set {
                this.routingCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool CheckForMismatch {
            get {
                return this.checkForMismatchField;
            }
            set {
                this.checkForMismatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckForMismatchSpecified {
            get {
                return this.checkForMismatchFieldSpecified;
            }
            set {
                this.checkForMismatchFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CarrierCodeType CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarrierCodeSpecified {
            get {
                return this.carrierCodeFieldSpecified;
            }
            set {
                this.carrierCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class WebAuthenticationDetail {
        
        private WebAuthenticationCredential parentCredentialField;
        
        private WebAuthenticationCredential userCredentialField;
        
        /// <remarks/>
        public WebAuthenticationCredential ParentCredential {
            get {
                return this.parentCredentialField;
            }
            set {
                this.parentCredentialField = value;
            }
        }
        
        /// <remarks/>
        public WebAuthenticationCredential UserCredential {
            get {
                return this.userCredentialField;
            }
            set {
                this.userCredentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class WebAuthenticationCredential {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class LocationDescription {
        
        private string locationIdField;
        
        private int locationNumberField;
        
        private bool locationNumberFieldSpecified;
        
        private string countryCodeField;
        
        private string stateOrProvinceCodeField;
        
        private string postalCodeField;
        
        private string serviceAreaField;
        
        private string airportIdField;
        
        private PackageSpecialServiceType[] restrictedPackageSpecialServicesField;
        
        private ShipmentSpecialServiceType[] restrictedShipmentSpecialServicesField;
        
        private bool fedExEuropeFirstOriginField;
        
        private bool fedExEuropeFirstOriginFieldSpecified;
        
        /// <remarks/>
        public string LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public int LocationNumber {
            get {
                return this.locationNumberField;
            }
            set {
                this.locationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationNumberSpecified {
            get {
                return this.locationNumberFieldSpecified;
            }
            set {
                this.locationNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StateOrProvinceCode {
            get {
                return this.stateOrProvinceCodeField;
            }
            set {
                this.stateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceArea {
            get {
                return this.serviceAreaField;
            }
            set {
                this.serviceAreaField = value;
            }
        }
        
        /// <remarks/>
        public string AirportId {
            get {
                return this.airportIdField;
            }
            set {
                this.airportIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RestrictedPackageSpecialServices")]
        public PackageSpecialServiceType[] RestrictedPackageSpecialServices {
            get {
                return this.restrictedPackageSpecialServicesField;
            }
            set {
                this.restrictedPackageSpecialServicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RestrictedShipmentSpecialServices")]
        public ShipmentSpecialServiceType[] RestrictedShipmentSpecialServices {
            get {
                return this.restrictedShipmentSpecialServicesField;
            }
            set {
                this.restrictedShipmentSpecialServicesField = value;
            }
        }
        
        /// <remarks/>
        public bool FedExEuropeFirstOrigin {
            get {
                return this.fedExEuropeFirstOriginField;
            }
            set {
                this.fedExEuropeFirstOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FedExEuropeFirstOriginSpecified {
            get {
                return this.fedExEuropeFirstOriginFieldSpecified;
            }
            set {
                this.fedExEuropeFirstOriginFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public enum PackageSpecialServiceType {
        
        /// <remarks/>
        ALCOHOL,
        
        /// <remarks/>
        APPOINTMENT_DELIVERY,
        
        /// <remarks/>
        COD,
        
        /// <remarks/>
        DANGEROUS_GOODS,
        
        /// <remarks/>
        DRY_ICE,
        
        /// <remarks/>
        NON_STANDARD_CONTAINER,
        
        /// <remarks/>
        PIECE_COUNT_VERIFICATION,
        
        /// <remarks/>
        PRIORITY_ALERT,
        
        /// <remarks/>
        SIGNATURE_OPTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public enum ShipmentSpecialServiceType {
        
        /// <remarks/>
        BLIND_SHIPMENT,
        
        /// <remarks/>
        BROKER_SELECT_OPTION,
        
        /// <remarks/>
        CALL_BEFORE_DELIVERY,
        
        /// <remarks/>
        COD,
        
        /// <remarks/>
        COD_REMITTANCE,
        
        /// <remarks/>
        CUSTOM_DELIVERY_WINDOW,
        
        /// <remarks/>
        CUT_FLOWERS,
        
        /// <remarks/>
        DANGEROUS_GOODS,
        
        /// <remarks/>
        DELIVERY_ON_INVOICE_ACCEPTANCE,
        
        /// <remarks/>
        DETENTION,
        
        /// <remarks/>
        DO_NOT_BREAK_DOWN_PALLETS,
        
        /// <remarks/>
        DO_NOT_STACK_PALLETS,
        
        /// <remarks/>
        DRY_ICE,
        
        /// <remarks/>
        EAST_COAST_SPECIAL,
        
        /// <remarks/>
        ELECTRONIC_TRADE_DOCUMENTS,
        
        /// <remarks/>
        EMAIL_NOTIFICATION,
        
        /// <remarks/>
        EXCLUSIVE_USE,
        
        /// <remarks/>
        EXHIBITION_DELIVERY,
        
        /// <remarks/>
        EXHIBITION_PICKUP,
        
        /// <remarks/>
        EXPEDITED_ALTERNATE_DELIVERY_ROUTE,
        
        /// <remarks/>
        EXPEDITED_ONE_DAY_EARLIER,
        
        /// <remarks/>
        EXPEDITED_SERVICE_MONITORING_AND_DELIVERY,
        
        /// <remarks/>
        EXPEDITED_STANDARD_DAY_EARLY_DELIVERY,
        
        /// <remarks/>
        EXTRA_LABOR,
        
        /// <remarks/>
        EXTREME_LENGTH,
        
        /// <remarks/>
        FEDEX_ONE_RATE,
        
        /// <remarks/>
        FLATBED_TRAILER,
        
        /// <remarks/>
        FOOD,
        
        /// <remarks/>
        FREIGHT_GUARANTEE,
        
        /// <remarks/>
        FREIGHT_TO_COLLECT,
        
        /// <remarks/>
        FUTURE_DAY_SHIPMENT,
        
        /// <remarks/>
        HOLD_AT_LOCATION,
        
        /// <remarks/>
        HOLIDAY_DELIVERY,
        
        /// <remarks/>
        HOLIDAY_GUARANTEE,
        
        /// <remarks/>
        HOME_DELIVERY_PREMIUM,
        
        /// <remarks/>
        INSIDE_DELIVERY,
        
        /// <remarks/>
        INSIDE_PICKUP,
        
        /// <remarks/>
        INTERNATIONAL_CONTROLLED_EXPORT_SERVICE,
        
        /// <remarks/>
        INTERNATIONAL_MAIL_SERVICE,
        
        /// <remarks/>
        INTERNATIONAL_TRAFFIC_IN_ARMS_REGULATIONS,
        
        /// <remarks/>
        LIFTGATE_DELIVERY,
        
        /// <remarks/>
        LIFTGATE_PICKUP,
        
        /// <remarks/>
        LIMITED_ACCESS_DELIVERY,
        
        /// <remarks/>
        LIMITED_ACCESS_PICKUP,
        
        /// <remarks/>
        MARKING_OR_TAGGING,
        
        /// <remarks/>
        NON_BUSINESS_TIME,
        
        /// <remarks/>
        PALLETS_PROVIDED,
        
        /// <remarks/>
        PALLET_SHRINKWRAP,
        
        /// <remarks/>
        PALLET_WEIGHT_ALLOWANCE,
        
        /// <remarks/>
        PENDING_COMPLETE,
        
        /// <remarks/>
        PENDING_SHIPMENT,
        
        /// <remarks/>
        PERMIT,
        
        /// <remarks/>
        PHARMACY_DELIVERY,
        
        /// <remarks/>
        POISON,
        
        /// <remarks/>
        PORT_DELIVERY,
        
        /// <remarks/>
        PORT_PICKUP,
        
        /// <remarks/>
        PRE_DELIVERY_NOTIFICATION,
        
        /// <remarks/>
        PRE_EIG_PROCESSING,
        
        /// <remarks/>
        PRE_MULTIPLIER_PROCESSING,
        
        /// <remarks/>
        PROTECTION_FROM_FREEZING,
        
        /// <remarks/>
        REGIONAL_MALL_DELIVERY,
        
        /// <remarks/>
        REGIONAL_MALL_PICKUP,
        
        /// <remarks/>
        RETURNS_CLEARANCE,
        
        /// <remarks/>
        RETURNS_CLEARANCE_SPECIAL_ROUTING_REQUIRED,
        
        /// <remarks/>
        RETURN_SHIPMENT,
        
        /// <remarks/>
        SATURDAY_DELIVERY,
        
        /// <remarks/>
        SATURDAY_PICKUP,
        
        /// <remarks/>
        SHIPMENT_ASSEMBLY,
        
        /// <remarks/>
        SORT_AND_SEGREGATE,
        
        /// <remarks/>
        SPECIAL_DELIVERY,
        
        /// <remarks/>
        SPECIAL_EQUIPMENT,
        
        /// <remarks/>
        STORAGE,
        
        /// <remarks/>
        SUNDAY_DELIVERY,
        
        /// <remarks/>
        THIRD_PARTY_CONSIGNEE,
        
        /// <remarks/>
        TOP_LOAD,
        
        /// <remarks/>
        USPS_DELIVERY,
        
        /// <remarks/>
        USPS_PICKUP,
        
        /// <remarks/>
        WEIGHING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class PostalDetail {
        
        private string stateOrProvinceCodeField;
        
        private string cityFirstInitialsField;
        
        private string cleanedPostalCodeField;
        
        private LocationDescription[] locationDescriptionsField;
        
        /// <remarks/>
        public string StateOrProvinceCode {
            get {
                return this.stateOrProvinceCodeField;
            }
            set {
                this.stateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityFirstInitials {
            get {
                return this.cityFirstInitialsField;
            }
            set {
                this.cityFirstInitialsField = value;
            }
        }
        
        /// <remarks/>
        public string CleanedPostalCode {
            get {
                return this.cleanedPostalCodeField;
            }
            set {
                this.cleanedPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocationDescriptions")]
        public LocationDescription[] LocationDescriptions {
            get {
                return this.locationDescriptionsField;
            }
            set {
                this.locationDescriptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class NotificationParameter {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class Notification {
        
        private NotificationSeverityType severityField;
        
        private bool severityFieldSpecified;
        
        private string sourceField;
        
        private string codeField;
        
        private string messageField;
        
        private string localizedMessageField;
        
        private NotificationParameter[] messageParametersField;
        
        /// <remarks/>
        public NotificationSeverityType Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeveritySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string LocalizedMessage {
            get {
                return this.localizedMessageField;
            }
            set {
                this.localizedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageParameters")]
        public NotificationParameter[] MessageParameters {
            get {
                return this.messageParametersField;
            }
            set {
                this.messageParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public enum NotificationSeverityType {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        NOTE,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class ValidatePostalReply {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private PostalDetail postalDetailField;
        
        /// <remarks/>
        public NotificationSeverityType HighestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications")]
        public Notification[] Notifications {
            get {
                return this.notificationsField;
            }
            set {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public PostalDetail PostalDetail {
            get {
                return this.postalDetailField;
            }
            set {
                this.postalDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class TransactionDetail {
        
        private string customerTransactionIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string CustomerTransactionId {
            get {
                return this.customerTransactionIdField;
            }
            set {
                this.customerTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class Localization {
        
        private string languageCodeField;
        
        private string localeCodeField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleCode {
            get {
                return this.localeCodeField;
            }
            set {
                this.localeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class VersionId {
        
        private string serviceIdField;
        
        private int majorField;
        
        private int intermediateField;
        
        private int minorField;
        
        public VersionId() {
            this.serviceIdField = "cnty";
            this.majorField = 4;
            this.intermediateField = 0;
            this.minorField = 0;
        }
        
        /// <remarks/>
        public string ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public int Intermediate {
            get {
                return this.intermediateField;
            }
            set {
                this.intermediateField = value;
            }
        }
        
        /// <remarks/>
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class Address {
        
        private string[] streetLinesField;
        
        private string cityField;
        
        private string stateOrProvinceCodeField;
        
        private string postalCodeField;
        
        private string urbanizationCodeField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private bool residentialField;
        
        private bool residentialFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StreetLines")]
        public string[] StreetLines {
            get {
                return this.streetLinesField;
            }
            set {
                this.streetLinesField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateOrProvinceCode {
            get {
                return this.stateOrProvinceCodeField;
            }
            set {
                this.stateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UrbanizationCode {
            get {
                return this.urbanizationCodeField;
            }
            set {
                this.urbanizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public bool Residential {
            get {
                return this.residentialField;
            }
            set {
                this.residentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResidentialSpecified {
            get {
                return this.residentialFieldSpecified;
            }
            set {
                this.residentialFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public partial class ClientDetail {
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private string meterInstanceField;
        
        private string integratorIdField;
        
        private ExpressRegionCode regionField;
        
        private bool regionFieldSpecified;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNumber {
            get {
                return this.meterNumberField;
            }
            set {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MeterInstance {
            get {
                return this.meterInstanceField;
            }
            set {
                this.meterInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string IntegratorId {
            get {
                return this.integratorIdField;
            }
            set {
                this.integratorIdField = value;
            }
        }
        
        /// <remarks/>
        public ExpressRegionCode Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegionSpecified {
            get {
                return this.regionFieldSpecified;
            }
            set {
                this.regionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public enum ExpressRegionCode {
        
        /// <remarks/>
        APAC,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        EMEA,
        
        /// <remarks/>
        LAC,
        
        /// <remarks/>
        US,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/cnty/v4")]
    public enum CarrierCodeType {
        
        /// <remarks/>
        FDXC,
        
        /// <remarks/>
        FDXE,
        
        /// <remarks/>
        FDXG,
        
        /// <remarks/>
        FXCC,
        
        /// <remarks/>
        FXFR,
        
        /// <remarks/>
        FXSP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void validatePostalCompletedEventHandler(object sender, validatePostalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validatePostalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validatePostalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidatePostalReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidatePostalReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591